---
title: 'GEOG 6000 Advanced Geographical Data Analysis'
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author:
  - Simon Brewer^[School of Environment, Society and Sustainability, University of Utah, simon.brewer@ess.utah.edu]
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: flatly
    df_print: paged
    number_sections: false
    toc: false
    toc_float: false
---

# Introduction

Geographical research increasingly generates large and complex datasets. The course is designed to introduce students to:

- A suite of statistical techniques for the analysis of such datasets
- The interpretation of results generated 
- The appropriate (and inappropriate) use of these methods

Topics will include advanced regression analysis, the analysis of multivariate datasets, spatial analysis and modeling. Theory will be taught during lectures, but emphasis will be placed on the practical application of these techniques and best-use practices in the analysis of research datasets. The majority of topics will be accompanied by lab exercises using the statistical software R, as well as take-home exercises. Students will undertake a short research project using one or more of the techniques covered in the course.


# Labs

- [Installation instructions][install]
- Lab 1
    - [Lab notes][lab01r]
    - [Penguins dataset][penguins]
- Lab 2
    - [Lab notes][lab02r]
    - [Irish Education dataset][irished]
    - [Body temperature dataset][normtemp]
    - [Soil porosity dataset][soilporo]
    - [Land-cover and elevation dataset][landcover]
    - [Dissolved oxygen measurement dataset][maxdo]
- Lab 3
    - [Lab notes][lab03r]
    - [Using Quarto (optional)][lab03br]
    - [A simple regression dataset (*regrex.csv*)][regrex]
    - [Death rates in Virginia dataset][virginia]
    - [IPCC simulated annual global temperature dataset][ipcc1]
    - [Maunga Whau DEM][volcano]

- Lab 4
    - [Lab notes][lab04r]
    - [Southern California runoff dataset][socalro]
    - [Child and mother IQ dataset][childiq]
    - [Irish Education dataset][irished]
    - [Body temperature dataset][normtemp]
    - [US state characteristics dataset][us_state]
    - [R script to simulate coin tosses][coinr]
- Lab 5
    - [Lab notes][lab05r]
    - [Using ggplot2 (optional)][lab05br]
    - [Irish Education dataset][irished]
    - [Honor Student Award dataset][hsa]
    - [Turbine failure dataset][turbines]
    - [Mediterranean bird species dataset][island2]
    - [Penguins dataset][penguins]
    - [Orange tree dataset][orange]
    - [Gapminder dataset][gapminder]
    - [Death rates in Virginia dataset][virginia]
- Lab 6
    - [Lab notes][lab06r]
    - [Math achievement dataset][mathach]
    - [Species introduction dataset][species_intro]
    - [Daily ozone concentration dataset][ozone]
    - [Gapminder dataset][gapminder]

[install]: https://simonbrewer.github.io/geog6000/GEOG_6000_00_Installation_instructions.html
[lab01r]: https://simonbrewer.github.io/geog6000/GEOG_6000_Lab_01_Introduction_to_R.html
[lab02r]: https://simonbrewer.github.io/geog6000/GEOG_6000_Lab_02_Inference.html
[lab03r]: https://simonbrewer.github.io/geog6000/GEOG_6000_Lab_03_Modeling_1.html
[lab03br]: https://simonbrewer.github.io/geog6000/GEOG_6000_Lab_03b_Reproducible_Research_R.html
[lab04r]: https://simonbrewer.github.io/geog6000/GEOG_6000_Lab_04_Modeling_2.html
[lab05r]: https://simonbrewer.github.io/geog6000/GEOG_6000_Lab_05_Models_3.html
[lab05br]: https://simonbrewer.github.io/geog6000/GEOG_6000_Lab_05b_Plotting_with_ggplot2.html
[lab06r]: https://simonbrewer.github.io/geog6000/GEOG_6000_Lab_06_Models_4.html

[penguins]: https://drive.google.com/file/d/1Xuk1wqGeJJZ__LHerIn8ghFhA0OmGHOH/view?usp=sharing
[irished]: https://drive.google.com/file/d/1OFEvB0pYtLUsD30b1FB79FMHlqo4o235/view?usp=sharing
[normtemp]: https://drive.google.com/file/d/1IfK3stapqe52EhFZSzP47aVS-NWQ-ecW/view?usp=sharing
[soilporo]: https://drive.google.com/file/d/1oEN33fGuIsxW89wDVp_j4ehBlsELkcf-/view?usp=sharing
[landcover]: https://drive.google.com/file/d/19fd8ZX9l_otHuV6nY9wFz833MQoyfak0/view?usp=sharing
[maxdo]: https://drive.google.com/file/d/1XkUZVWqgu7HYCkr7kiJy5wpmqSXR1PCX/view?usp=sharing
[regrex]: https://drive.google.com/file/d/1YUmoiJLtiXIL5k-G4N6ILXik762nxPIE/view?usp=sharing
[virginia]: https://drive.google.com/file/d/1jl95_YLSiQqvi_0De4xJ_ZFc3WbUZEbZ/view?usp=sharing
[ipcc1]: https://drive.google.com/file/d/1VMvh1THqbCutiyGGrWsDFisQB1kZAcHs/view?usp=sharing
[volcano]: https://drive.google.com/file/d/1Lo4DdH6mspBuNRJJBZnjT5RXuBdojQlr/view?usp=sharing
[socalro]: https://drive.google.com/file/d/1nK4WbnWzF2oyFPUjya9x0cog6NlbACWy/view?usp=sharing
[childiq]: https://drive.google.com/file/d/1QRlMg3WG-Uwhpj1mrGH6bZoOW6Dq3fZx/view?usp=sharing
[us_state]: https://drive.google.com/file/d/10o6kGfVhQ5iLc0WO2-O5HwocEXpm0ou5/view?usp=sharing
[coinr]: https://drive.google.com/file/d/1qVn-U1hbNDi2jkZZqfhQmUhkaL-giKon/view?usp=sharing
[hsa]: https://drive.google.com/file/d/1Z4oC7N264bQLnQX-xEQf6agywLqo4X5z/view?usp=sharing
[turbines]: https://drive.google.com/file/d/1cSG8qkZ_oJMQ9goWe9o5OtZdcMEZ3Jc7/view?usp=sharing
[island2]: https://drive.google.com/file/d/1JcwjP_fT4BaDvU9nvs6T1yyEIwyfA2zQ/view?usp=sharing
[orange]: https://drive.google.com/file/d/1hbmR-6nPMMleLclqSCfO0o6rrcLJIxN2/view?usp=sharing
[gapminder]: https://drive.google.com/file/d/13R0mVaV92US7LsfWRV0gICHvthSxnCNN/view?usp=sharing
[mathach]: https://drive.google.com/file/d/1TELYyaE8CIWEkJkSDLIMcs-dHKGajP0q/view?usp=sharing
[species_intro]: https://drive.google.com/file/d/19T6Db7NRBtFIWjmSL56iRlAYrus2q7vP/view?usp=sharing
[ozone]: https://drive.google.com/file/d/1Gj6yI938BB4nloqz0GPoI70tffDlQ6Ku/view?usp=sharing